### ISSUE TITLE
I cloned it, and installed it, and surprised by "Hello, world!"!

### ISSUE THREAD

**Issue by xieyuheng** [uuid-rs/ruuhid#1]
What's the plan here ?
Can I contribute ?

**Comment by Dylan-DPC-zz** [comment]
Hi @xieyuheng 

Yeah we have kept this on the backburner for sometime. If you want to contribute you can create a "cli app"  using clap or structopt and we will discuss what to do next after that.

For reference you can use the [CLI Book](https://rust-lang-nursery.github.io/cli-wg/)

**Comment by xieyuheng** [comment]
https://github.com/uuid-rs/uuid_cli/pull/2
