### ISSUE TITLE
The interface of uuid_cli

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/ruuhid#3]
I just want a discussion on how the interface should look like.

On one hand we have the [ossp uuid](https://linux.die.net/man/1/uuid) that most is well known for anyone using *nix OSes. I however find the interface slightly awkward. Combination of expected flags can produce unexpected results(Telling from experience and experimentation.)

Edit:

An even better known [uuidgen](http://man7.org/linux/man-pages/man1/uuidgen.1.html) also exists and apparently is installed by default on several linux distros, and may be a better contender than ossp uuid.

On the other hand a new interface would help build from experience to rectify the mistakes. This however would mean that our binary would be breaking and would lose the dropin replacement value that I do want with this project.

So I am looking for opinions here

**Comment by dongcarl** [comment]
Perhaps what can be done is to have it act in a "compatibility mode" when invoked as `uuid`, and act in a "enhanced UI mode" when invoked as `ruuid`. This can be achieved by looking at `argv[0]` I believe.

**Comment by kinggoesgaming** [comment]
looking around I also found about [uuidgen](http://man7.org/linux/man-pages/man1/uuidgen.1.html)

**Comment by kinggoesgaming** [comment]
@dongcarl we are using structopt( hence backed by clap-rs) so pretty sure a subcommand system may even work

**Comment by LeonardMH** [comment]
There is also a uuidgen shipped with macOS, it produces a v4 UUID by default (which is the only sane option) and as far as I can tell there aren't any other options to the tool. Please default to a v4 UUID.

[This article](https://blog.kgriffs.com/2015/03/03/towards-a-better-uuidgen.html) also rightfully points out that the output from a uuid tool should be easily pipe-able.

**Comment by kinggoesgaming** [comment]
ok so thinking over this... I think I will go with `uuidgen` syntax with subcommand extensions for extra behaviour.

**Comment by kinggoesgaming** [comment]
@LeonardMH I noticed in the article (osx) that `uuidgen` uses uppercase hex when printing the uuids while on linux it uses lowercase hex. Is it for any significant reason?

Looking up on the topic only seems to find articles on how to use `awk` or `tr` the uppercase uuid to lowercase

**Comment by LeonardMH** [comment]
I don't believe it is significant. That's just a hex representation of the number, the hyphenation and capitalization is essentially arbitrary.

I tend to prefer representing hex numbers with uppercase letters because you get all equal height characters, but the canonical reference for UUIDs ([rfc4122](https://tools.ietf.org/html/rfc4122), check the appendices) uses lowercase letters so that's probably the default I would use.

**Comment by kinggoesgaming** [comment]
Its been a while since I used a mac and I know Apple and Microsoft have a tendency of breaking from the norm so just confirming

**Comment by kinggoesgaming** [comment]
The base interface has been defined...  Individual subcommands will probably have their own issues

Closing
